language: ruby
rvm:
  - 1.9.3
script: bundle exec rake unit_tests
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org##jenins-api-client"
