language: ruby
rvm:
  - 1.9.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq jenkins
  - echo `service jenkins status`
  - echo `curl 127.0.0.1:8080`
  - echo `curl 127.0.0.1`
  - echo `curl localhost`
  - echo `ifconfig`
  - echo `hostname`
  - echo `netstat -an`
  - echo `/sbin/ifconfig eth0 | grep "inet addr" | awk -F: '{print $2}' | awk '{print $1}'`
script: bundle exec rspec
