language: ruby
rvm:
  - 1.9.3
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq jenkins
  - echo `service jenkins status`
  - echo `curl 10.0.2.15:8080`
  - echo `curl 10.0.2.15`
  - echo `curl localhost`
  - echo `ifconfig`
  - echo `hostname`
  - echo `netstat -an`
script: bundle exec rspec
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.org##arangamani"
